{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace }}-keycloak
  name: {{ .Values.namespace }}-keycloak-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.namespace }}-keycloak
{{- end }}