# Namespace for kubernetes cluster
namespace: consentbb
# Resource constraints for a pod
resources: {}
# Security context for a pod
securityContext:
  runAsUser: 0

# Postgres
postgres:
  enabled: true
  # Container image
  image: bitnami/postgresql:14.10.0
  # Username
  username: bn_keycloak
  # Password
  password: bn_keycloak
  # Database name
  database: bitnami_keycloak

# Keycloak
keycloak:
  enabled: true
  # Container image
  image: docker.io/bitnami/keycloak:22.0.2-debian-11-r0
  # Username
  adminUsername: admin
  # Password
  adminPassword: admin
  # Database user password
  dbPassword: bn_keycloak
  # Ingress
  ingress:
    # Annotations for the ingress
    annotations:
      # Default annotations if ingress is nginx ingress
      # Allow HTTP false
      kubernetes.io/ingress.allow-http: "false"
      # Ingress class as NGINX
      kubernetes.io/ingress.class: nginx
      # Enable CORS
      nginx.ingress.kubernetes.io/enable-cors: "true"
      # Proxy buffer size
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    # Hosts
    hosts:
      - host: test-keycloak.igrant.io
        paths:
          - path: /
            pathType: Prefix
    # TLS
    tls:
      - hosts:
          - test-keycloak.igrant.io
        secretName: tls-secret

# Mongodb
mongo:
  enabled: true
  # Container image
  image: bitnami/mongodb:7.0
  username: bb-consent-user
  password: bb-consent-password
  database: bb-consent-consentdb

# API
api:
  enabled: true
  # Container image
  image: igrantio/bb-consent-api:2023.11.12
  # Ingress
  ingress:
    # Annotations for the ingress
    annotations:
      # Default annotations if ingress is nginx ingress
      # Allow HTTP false
      kubernetes.io/ingress.allow-http: "false"
      # Ingress class as NGINX
      kubernetes.io/ingress.class: nginx
      # Enable CORS
      nginx.ingress.kubernetes.io/enable-cors: "true"
      # Proxy buffer size
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    # Hosts
    hosts:
      - host: consentbb-api.igrant.io
        paths:
          - path: /
            pathType: Prefix
          - path: /*
            pathType: Prefix
    # TLS
    tls:
      - hosts:
          - consentbb-api.igrant.io
        secretName: tls-secret
  # Configuration
  configuration:
    # Organisation
    Organization:
      # Organisation name
      name:
      # Organisation location
      location:
      # Organisation description
      description:
      # Organisation EULA URL
      eulaUrl:
    # Organisation admin user
    User:
      # Organisation admin username
      username:
      # Organisation admin password
      password:
    # API key secret to generate and verify API keys
    ApiSecretKey:
    # Organisation type/industry sector name
    Type:
      name:
    # Keycloak
    Iam:
      # Keycloak URL accessible from the internet
      url:
      # Keycloak realm name
      realm:
      # Keycloak client id
      ClientId:
    # SMTP server
    Smtp:
      # SMTP username
      username:
      # SMTP password
      password:
      # SMTP host
      host:
      # SMTP port
      port: 587
      # From email
      adminEmail:
    # Webhook
    Webhooks:
      # Webhooks events enabled for subscription
      events:
        - consent.allowed
        - consent.disallowed
    # Privacy dashboard deployment details to be displayed in admin dashboard
    PrivacyDashboardDeployment:
      # Privacy dashboard hostname
      Hostname:
      # Privacy dashboard version
      Version:
    # Data policy
    Policy:
      # Data policy name
      Name:
      # Data policy URL
      Url:
      # Industry sector
      IndustrySector:
      # Geographic restriction
      GeographicRestriction:
      # Storage location
      StorageLocation:

# Admin dashboard
adminDashboard:
  enabled: true
  # Container image
  image: igrantio/bb-consent-admin-dashboard:2023.11.5
  # Ingress
  ingress:
    # Annotations for the ingress
    annotations:
      # Default annotations if ingress is nginx ingress
      # Allow HTTP false
      kubernetes.io/ingress.allow-http: "false"
      # Ingress class as NGINX
      kubernetes.io/ingress.class: nginx
      # Enable CORS
      nginx.ingress.kubernetes.io/enable-cors: "true"
      # Proxy buffer size
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    # Hosts
    hosts:
      - host: consentbb-admin-dashboard.igrant.io
        paths:
          - path: /
            pathType: Prefix
          - path: /*
            pathType: Prefix
    # TLS
    tls:
      - hosts:
          - consentbb-admin-dashboard.igrant.io
        secretName: tls-secret
  # Configuration
  configuration:
    # Consent BB API server base URL
    baseUrl:
    # Admin dashboard version
    appVersion: 2023.11.5
    # Client id as mentioned in Consent BB API server IAM configuration
    clientId:

# Privacy dashboard
privacyDashboard:
  enabled: true
  # Container image
  image: igrantio/bb-consent-privacy-dashboard:2023.11.5
  # Ingress
  ingress:
    # Annotations for the ingress
    annotations:
      # Default annotations if ingress is nginx ingress
      # Allow HTTP false
      kubernetes.io/ingress.allow-http: "false"
      # Ingress class as NGINX
      kubernetes.io/ingress.class: nginx
      # Enable CORS
      nginx.ingress.kubernetes.io/enable-cors: "true"
      # Proxy buffer size
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    # Hosts
    hosts:
      - host: consentbb-privacy-dashboard.igrant.io
        paths:
          - path: /
            pathType: Prefix
          - path: /*
            pathType: Prefix
    # TLS
    tls:
      - hosts:
          - consentbb-privacy-dashboard.igrant.io
        secretName: tls-secret
  # Configuration
  configuration:
    # Consent BB API server base URL
    baseUrl:
    # Redirect URL if external authenticatio mechanism is configured
    # in admin dashboard. This is so that after the individual logins to external IDP,
    # it will redirect back to this URL. It should always be privacy dashboard URL + /login
    # For .e.g https://demo-consent-bb-privacy-dashboard.igrant.io/login
    redirectUrl:
    # Client id as mentioned in Consent BB API server IAM configuration
    clientId: