apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namespace }}-mongo-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard