apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.namespace }}-mongo
  name: {{ .Values.namespace }}-mongo-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    run: {{ .Values.namespace }}-mongo
