{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.namespace }}-{{ .Values.prefix }}-mongo
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-mongo-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    run: {{ .Values.namespace }}-{{ .Values.prefix }}-mongo
{{- end }}