{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-api
  name: {{ .Values.namespace }}-{{ .Values.prefix }}-api-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.namespace }}-{{ .Values.prefix }}-api
{{- end }}