apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.namespace }}-api
  name: {{ .Values.namespace }}-api-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.namespace }}-api
