apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: consentbb-mongo
  name: consentbb-mongo
  namespace: consentbb
spec:
  selector:
    matchLabels:
      run: consentbb-mongo
  template:
    metadata:
      labels:
        run: consentbb-mongo
    spec:
      containers:
        - env:
            - name: MONGODB_APPLICATION_DATABASE
              value: <>
            - name: MONGODB_APPLICATION_USER
              value: <>
            - name: MONGODB_APPLICATION_PASSWORD
              value: <>
          image: eu.gcr.io/jenkins-189019/igrant-mongo:4.0.4
          imagePullPolicy: IfNotPresent
          name: consentbb-mongo
          resources: {}
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: consentbb-mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consentbb-mongo-pvc
  namespace: consentbb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: consentbb-mongo
  name: consentbb-mongo-svc
  namespace: consentbb
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    run: consentbb-mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consentbb-privacy-dashboard
  name: consentbb-privacy-dashboard-svc
  namespace: consentbb
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: consentbb-privacy-dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: consentbb-privacy-dashboard-ing
  namespace: consentbb
spec:
  rules:
    - host: consentbb-privacy-dashboard.igrant.io
      http:
        paths:
          - backend:
              service:
                name: consentbb-privacy-dashboard-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: consentbb-privacy-dashboard-svc
                port:
                  number: 80
            path: /*
            pathType: Prefix
  tls:
    - hosts:
        - consentbb-privacy-dashboard.igrant.io
      secretName: tls-secret-govstack
