apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consentbb-mongo-pvc
  namespace: consentbb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
