apiVersion: v1
kind: Service
metadata:
  labels:
    run: consentbb-mongo
  name: consentbb-mongo-svc
  namespace: consentbb
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    run: consentbb-mongo
